### PR TITLE
Enhance copy loop functionality by allowing `reference()` usage in copy mode

### LINKED ISSUE #1286: Use `reference()` in `copy()` loop throws not implemented
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the latest version
- [x] Search the existing issues.

### Summary

As a configuration author, I want the ability to use the `reference()` function in `copy()` loop. However, the current implementation throws an error: Error: Parser: The 'reference()' function cannot be used when processing a 'Copy' loop.

According to the ARM docs, this should be possible.

### Steps to reproduce

1. Create the following configuration document (using `DatabricksDsc` module):

```yaml
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
parameters:
  workspaceUrl:
    type: string
  accessToken:
    type: string
    defaultValue: "[envvar('BEARER_TOKEN')]"
  dabConfiguration:
    type: object
  uamiConfiguration:
    type: object
  clusterConfiguration:
    type: object
  clusterPolicies:
    type: array
    defaultValue:
    - smallClusterPolicy
    - mediumClusterPolicy
    - largeClusterPolicy
resources:
  - name: "[format('{0}', parameters('clusterConfiguration')[parameters('clusterPolicies')[copyIndex()]].name)]"
    copy:
      name: clusterPolicyLoop
      count: "[length(parameters('clusterPolicies'))]"
    type: DatabricksDsc/DatabricksClusterPolicy
    properties:
      WorkspaceUrl: "[parameters('workspaceUrl')]"
      AccessToken: "[parameters('accessToken')]"
      Name: "[parameters('clusterConfiguration')[parameters('clusterPolicies')[copyIndex()]].name]"
      Description: "[parameters('clusterConfiguration')[parameters('clusterPolicies')[copyIndex()]].description]"
      Definition: "[parameters('clusterConfiguration')[parameters('clusterPolicies')[copyIndex()]].definition]"

  - name: "[format('{0} permission', parameters('clusterConfiguration')[parameters('clusterPolicies')[copyIndex()]].name)]"
    copy:
      name: clusterPolicyPermissionLoop
      count: "[length(parameters('clusterPolicies'))]"
    dependsOn:
      - "[resourceId('DatabricksDsc/DatabricksClusterPolicy', parameters('clusterConfiguration')[parameters('clusterPolicies')[copyIndex()]].name)]"
    type: DatabricksDsc/DatabricksClusterPolicyPermission
    properties:
      WorkspaceUrl: "[parameters('workspaceUrl')]"
      AccessToken: "[parameters('accessToken')]"
      ClusterPolicyId: "[reference(resourceId('DatabricksDsc/DatabricksClusterPolicy', parameters('clusterConfiguration')[parameters('clusterPolicies')[copyIndex()]].name)).PolicyId]"
      AccessControlList:
      - ServicePrincipalName: "[parameters('dabConfiguration').servicePrincipalId]"
        PermissionLevel: 'CAN_USE'
```

### Expected behavior

```console
The copy loop works, referencing the earlier created resources.
```

### Actual behavior

```console
Error: Parser: The 'reference()' function cannot be used when processing a 'Copy' loop
```

### Error details

```console

```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.5.4
PSEdition                      Core
GitCommitId                    7.5.4
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

dsc 3.2.0-preview.8

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by Gijsreyn**
# PR Summary

Fixed copy loops to work with `reference()` function by preserving copy context during property evaluation. Modified `copyIndex()` and `reference()` to accept copy context outside Copy mode, and stored loop indices in resource tags during unrolling then restored them before evaluating properties. Tests added

## PR Context

Fix #1286

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@Gijsreyn can you fix the merge conflicts?

**Comment by Gijsreyn** [comment]
@SteveL-MSFT - I'll pick it up when I'm back.

**Comment by Gijsreyn** [comment]
@SteveL-MSFT - I tried resolving the merge conflicts, but it looks like after the SSH merge, it started failing: https://github.com/PowerShell/DSC/actions/runs/20111826751

**Comment by SteveL-MSFT** [comment]
@Gijsreyn I understand the problem and working on a fix

**Comment by SteveL-MSFT** [comment]
@Gijsreyn build issue resolved, but you still have some test failures

**Comment by Gijsreyn** [comment]
@SteveL-MSFT  - oops, I think I removed too much when fixing the merge conflict. Should be good to go!

File: lib/dsc-lib/src/configure/depends_on.rs [hunk 1]
```diff
@@ -110,15 +154,59 @@ fn unroll_and_push(order: &mut Vec<Resource>, resource: &Resource, parser: &mut
...
+                  }
+
+                  // Check if the dependency is also in copy_resources we're building
+                  if copy_resources.iter().any(|r| r.name == resource_name && r.resource_type == resource_type) {
+                      continue;
+                  }
+
+                  // Find the dependency in config.resources - it might be a copy loop template
+                  // We need to find by type since the name is the template expression
+                  if let Some(dependency_resource) = config.resources.iter().find(|r| r.resource_type == resource_type) {
```
Comment (SteveL-MSFT) [inline lib/dsc-lib/src/configure/depends_on.rs]: Do we need to handle the ase where the dependency doesn't exist?

File: lib/dsc-lib/src/configure/depends_on.rs [hunk 2]
```diff
@@ -110,15 +154,59 @@ fn unroll_and_push(order: &mut Vec<Resource>, resource: &Resource, parser: &mut
...
           let Value::String(new_name) = parser.parse_and_execute(&resource.name, context)? else {
               return Err(DscError::Parser(t!("configure.mod.copyNameResultNotString").to_string()))
           };
           new_resource.name = new_name.to_string();
 
-          if let Some(properties) = &resource.properties {
-              new_resource.properties = invoke_property_expressions(parser, context, Some(properties))?;
-          }
+          // Store copy loop context in resource tags for later use by reference()
+          let mut tags = new_resource.tags.clone().unwrap_or_default();
```
Comment (SteveL-MSFT) [inline lib/dsc-lib/src/configure/depends_on.rs]: If you need to keep some context information I would prefer to put it under `metadata/Microsoft.DSC`

Comment (Gijsreyn) [reply lib/dsc-lib/src/configure/depends_on.rs]: Added it under `Microsoft.DSC/copyLoops`.

File: lib/dsc-lib/src/configure/depends_on.rs (hunk 1 above)
Comment (Gijsreyn) [reply lib/dsc-lib/src/configure/depends_on.rs]: Good catch, modified it

File: lib/dsc-lib/src/configure/depends_on.rs [hunk 3]
```diff
@@ -35,36 +35,39 @@ pub fn get_resource_invocation_order(config: &Configuration, parser: &mut Statem
...
-                }
-                // see if the dependency is already in the order
-                if order.iter().any(|r| r.name == resource_name && r.resource_type == resource_type) {
-                    continue;
+                    if order.iter().any(|r| r.name == resource_name && r.resource_type == resource_type) {
+                        continue;
+                    }
+
+                    let Some(dependency_resource) = config.resources.iter().find(|r| r.name.eq(&resource_name)) else {
+                        return Err(DscError::Validation(t!("configure.dependsOn.dependencyNotFound", dependency_name = resource_name, resource_name = resource.name).to_string()));
```
Comment (SteveL-MSFT) [inline lib/dsc-lib/src/configure/depends_on.rs:54]: Please add a test case for this

File: lib/dsc-lib/src/configure/depends_on.rs [hunk 4]
```diff
@@ -111,15 +155,75 @@ fn unroll_and_push(order: &mut Vec<Resource>, resource: &Resource, parser: &mut
...
 
-          if let Some(properties) = &resource.properties {
-              new_resource.properties = invoke_property_expressions(parser, context, Some(properties))?;
-          }
+          // Store copy loop context in resource metadata under Microsoft.DSC for later use by reference()
+          let mut metadata = new_resource.metadata.clone().unwrap_or_else(|| {
+              use crate::configure::config_doc::Metadata;
+              use serde_json::Map;
+              Metadata {
+                  microsoft: None,
```
Comment (SteveL-MSFT) [inline lib/dsc-lib/src/configure/depends_on.rs:213]: You should modify. the `MicrosoftDscMetadata` struct with a new `copy_loop` property and put it there

**Comment by SteveL-MSFT** [comment]
@Gijsreyn can you fix the merge conflict?  otherwise looks good to me

**Comment by Gijsreyn** [comment]
@SteveL-MSFT - should be good to go (after the build finishes up).

**Review by SteveL-MSFT — APPROVED** [review]
