### PR TITLE
Export support for PS class-based resources

### LINKED ISSUE #183: Export support for provider-based resources
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Need a way to support Export operation for provider-based resources.

### Expected behavior

```console
NA
```

### Actual behavior

```console
NA
```

### Error details

_No response_

### Environment data

```PowerShell
NA
```

### Version

v1

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anmenaga**
# PR Summary

Fix #183 

2 updates:
1) Adds `Export` support for provider-based resources.
    It is done using `export` node in `*.dsc.resource.json` file similar to `get/set/test`.
2) Adds `Export` support to class-based PS resources.
   To support this a DscResource class has to implement a static `Export` function like so:

```
using namespace System.Collections.Generic

[DscResource()]
class TestClassResource
{
# omitting properties and Get,Set,Test methods here

    static [TestClassResource[]] Export()
    {
        $resultList = [List[TestClassResource]]::new()
        1..5 | %{
            $obj = New-Object TestClassResource
            $obj.Name = "Object$_"
            $obj.Prop1 = "Property of object$_"
            $resultList.Add($obj)
        }
        
        return $resultList.ToArray()
    }
}
```

### CODE REVIEW

File: dsc/src/resource_command.rs [hunk 1]
```diff
@@ -55,12 +55,24 @@ pub fn get(dsc: &DscManager, resource_type: &str, input: &Option<String>, stdin:
...
     };
+
     debug!("resource.type_name - {} implemented_as - {:?}", resource.type_name, resource.implemented_as);
-    let export_result = match resource.export() {
+    if let Some(requires) = &resource.requires {
+        input = add_type_name_to_json(input, resource.type_name.clone());
+        if let Some(pr) = get_resource(dsc, requires) {
+            resource = pr;
+        } else {
+            error!("Provider {} not found", requires);
```
Comment (SteveL-MSFT) [inline dsc/src/resource_command.rs:70]: We want to start putting identifiers in single quotes as it makes it easier reading the error message which resource is at fault

```suggestion
            error!("Provider '{}' not found", requires);
```

File: dsc/src/resource_command.rs [hunk 2]
```diff
@@ -55,12 +55,24 @@ pub fn get(dsc: &DscManager, resource_type: &str, input: &Option<String>, stdin:
...
+            return;
+        };
+    }
+
+    let export_result = match resource.export(input.as_str()) {
```
Comment (SteveL-MSFT) [inline dsc/src/resource_command.rs:75]: Use ref syntax instead of calling the function for consistency

```suggestion
    let export_result = match resource.export(&input) {
```

File: dsc/src/resource_command.rs [hunk 3]
```diff
@@ -203,14 +215,26 @@ pub fn schema(dsc: &DscManager, resource_type: &str, format: &Option<OutputForma
...
+        } else {
+            error!("Provider {} not found", requires);
+            return;
+        };
+    }
+
     let mut conf = Configuration::new();
 
-    if let Err(err) = add_resource_export_results_to_configuration(dsc_resource, &mut conf) {
+    if let Err(err) = add_resource_export_results_to_configuration(dsc_resource, provider_resource, &mut conf, input.as_str()) {
```
Comment (SteveL-MSFT) [inline dsc/src/resource_command.rs:237]:
```suggestion
    if let Err(err) = add_resource_export_results_to_configuration(dsc_resource, provider_resource, &mut conf, &input) {
```

File: dsc/src/resource_command.rs [hunk 4]
```diff
@@ -203,14 +215,26 @@ pub fn schema(dsc: &DscManager, resource_type: &str, format: &Option<OutputForma
...
         return
     };
 
+    let mut provider_resource: Option<&DscResource> = None;
+    if let Some(requires) = &dsc_resource.requires {
+        input = add_type_name_to_json(input, dsc_resource.type_name.clone());
+        if let Some(pr) = get_resource(dsc, requires) {
+            provider_resource = Some(pr);
+        } else {
+            error!("Provider {} not found", requires);
```
Comment (SteveL-MSFT) [inline dsc/src/resource_command.rs:230]:
```suggestion
            error!("Provider '{}' not found", requires);
```

File: powershellgroup/Tests/powershellgroup.config.tests.ps1 [hunk 5]
```diff
@@ -39,4 +39,24 @@ Describe 'PowerShellGroup resource tests' {
         $res.results.result.afterState[0].RebootRequired | Should -Not -BeNull
         $res.results.result.afterState[1].RebootRequired | Should -Not -BeNull
     }
+
+    It 'Export works on config with class-based resources' -Skip:(!$IsWindows){
```
Comment (SteveL-MSFT) [inline powershellgroup/Tests/powershellgroup.config.tests.ps1:43]: There shouldn't be a reason to skip on non Windows

File: powershellgroup/Tests/powershellgroup.config.tests.ps1 [hunk 6]
```diff
@@ -39,4 +39,24 @@ Describe 'PowerShellGroup resource tests' {
...
+                resources:
+                - name: Class-resource Info
+                  type: PSTestModule/TestClassResource
+'@
+        $out = $yaml | dsc config export
+        $LASTEXITCODE | Should -Be 0
+        $res = $out | ConvertFrom-Json
+        $res.'$schema' | Should -BeExactly 'https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json'
+        $res.'resources' | Should -Not -BeNullOrEmpty
+        $res.resources.count | Should -Be 5
```
Comment (SteveL-MSFT) [inline powershellgroup/Tests/powershellgroup.config.tests.ps1:60]: Since we control the output and know exactly what should be returned, we should validate at least the Name property of the objects.

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]
Fix build issues.  This design will allow class based resources implementing `export` to still work with DSC v2, right?  v2 should just ignore the new `export` method?  Ideally we should have a test to ensure we aren't breaking compat.

File: dsc/src/resource_command.rs (hunk 1 above)
Comment (anmenaga) [reply dsc/src/resource_command.rs:70]: Good point; fixed.

File: dsc/src/resource_command.rs (hunk 3 above)
Comment (anmenaga) [reply dsc/src/resource_command.rs:237]: Fixed.

File: dsc/src/resource_command.rs (hunk 4 above)
Comment (anmenaga) [reply dsc/src/resource_command.rs:230]: Fixed.

File: powershellgroup/Tests/powershellgroup.config.tests.ps1 (hunk 5 above)
Comment (anmenaga) [reply powershellgroup/Tests/powershellgroup.config.tests.ps1:43]: This export scenario still relies on PSDesiredStateConfiguration v2 (for resource discovery), which is not stable on non-windows.

File: powershellgroup/Tests/powershellgroup.config.tests.ps1 (hunk 6 above)
Comment (anmenaga) [reply powershellgroup/Tests/powershellgroup.config.tests.ps1:60]: Updated to check properties of the first object.

**Comment by anmenaga** [comment]
> This design will allow class based resources implementing `export` to still work with DSC v2, right?

Yes.

> v2 should just ignore the new `export` method?

Correct.

> Ideally we should have a test to ensure we aren't breaking compat.

We already test that implicitly. [We are using v2 throughout PowerShellGroup resource tests](https://github.com/PowerShell/DSC/blob/1fb90f6f9015658daeed21587f6bc6d2e9bbf454/build.ps1#L231).

**Review by SteveL-MSFT — APPROVED** [review]
