### PR TITLE
Switched to Tracing framework for diagnostic information

### LINKED ISSUE #158: Scrub printing calls
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Current `eprintln`/`println` calls throughout the code should be replaced with proper logging API calls to `dsc_lib\src\logger.rs`.

### Expected behavior

```console
_
```

### Actual behavior

```console
_
```

### Error details

_No response_

### Environment data

```PowerShell
_
```

### Version

v1

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anmenaga**
# PR Summary

Fix #158 

## PR Context

Replaced `eprintln!` calls with macros of the [Tracing framework for diagnostic information](https://docs.rs/tracing/latest/tracing/).

### CODE REVIEW

File: dsc_lib/src/dscerror.rs [hunk 1]
```diff
@@ -166,11 +167,11 @@ impl StreamMessage {
     pub fn print(&self, error_format:&StreamMessageType, warning_format:&StreamMessageType) -> Result<(), DscError>{
         if self.message_type == StreamMessageType::Error
         {
-            eprintln!("{:?} -> {} {}", error_format, self.resource_type_name, self.message);
+            error!("{:?} -> {} {}", error_format, self.resource_type_name, self.message);
         }
         if self.message_type == StreamMessageType::Warning
         {
-            eprintln!("{:?} -> {} {}", warning_format, self.resource_type_name, self.message);
+            error!("{:?} -> {} {}", warning_format, self.resource_type_name, self.message);
```
Comment (SteveL-MSFT) [inline dsc_lib/src/dscerror.rs:174]: should this be using `warning` instead of `error`?  For now, we can have subscriber write warnings to stderr.

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

File: dsc_lib/src/dscerror.rs [hunk 2]
```diff
@@ -166,11 +167,25 @@ impl StreamMessage {
     pub fn print(&self, error_format:&StreamMessageType, warning_format:&StreamMessageType) -> Result<(), DscError>{
```
Comment (SteveL-MSFT) [inline dsc_lib/src/dscerror.rs:167]: This function is only used during discovery.  We should change that to use `error!` instead and remove the need for this entirely.

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

File: dsc_lib/src/dscerror.rs (hunk 2 above)
Comment (anmenaga) [reply dsc_lib/src/dscerror.rs:167]: Yes; that is the plan for discovery refactoring.

Comment (anmenaga) [reply dsc_lib/src/dscerror.rs:174]: Added TODOs to remove this during discovery refactoring.

**Review by SteveL-MSFT — APPROVED** [review]
